package com.natica.sales.model.common.serviceinterface;

import com.natica.sales.model.views.common.SmartsBlokPlaniViewSDO;
import com.natica.sales.model.views.common.SmartsGyrmnklGorselViewSDO;
import com.natica.sales.model.views.common.SmartsPlanGayrimenkulViewSDO;
import com.natica.sales.model.views.common.SmartsVaziyetViewSDO;
import com.natica.sales.model.views.common.UnitsViewSDO;
import com.natica.sales.model.views.response.common.SmartsCrudResponseSDO;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 17:42:39 EET 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/com/natica/sales/model/common/", name="SalesModuleService", wsdlLocation="com/natica/sales/model/common/serviceinterface/SalesModuleService.wsdl")
@SDODatabinding(schemaLocation="com/natica/sales/model/common/serviceinterface/SalesModuleService.xsd")
public interface SalesModuleService {
    public static final String NAME = "{/com/natica/sales/model/common/}SalesModuleService";

    /**
     * Exported method createBlockPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/createBlockPlani", operationName="createBlockPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createBlockPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createBlockPlaniResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO createBlockPlani(@WebParam(mode = WebParam.Mode.IN, name="projectId")
        BigDecimal projectId, @WebParam(mode = WebParam.Mode.IN, name="blokPlaniGorseli")
        String blokPlaniGorseli, @WebParam(mode = WebParam.Mode.IN, name="KoorX")
        BigDecimal KoorX, @WebParam(mode = WebParam.Mode.IN, name="KoorY")
        BigDecimal KoorY) throws ServiceException;

    /**
     * Exported method createGayrimenkulGorsel from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/createGayrimenkulGorsel", operationName="createGayrimenkulGorsel")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createGayrimenkulGorsel")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createGayrimenkulGorselResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO createGayrimenkulGorsel(@WebParam(mode = WebParam.Mode.IN, name="gayrimenkulId")
        BigDecimal gayrimenkulId, @WebParam(mode = WebParam.Mode.IN, name="dosyaAdi")
        String dosyaAdi, @WebParam(mode = WebParam.Mode.IN, name="baslik")
        String baslik, @WebParam(mode = WebParam.Mode.IN, name="tip")
        BigDecimal tip, @WebParam(mode = WebParam.Mode.IN, name="sira")
        BigDecimal sira) throws ServiceException;

    /**
     * Exported method createPlanGayrimenkul from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/createPlanGayrimenkul", operationName="createPlanGayrimenkul")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createPlanGayrimenkul")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createPlanGayrimenkulResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO createPlanGayrimenkul(@WebParam(mode = WebParam.Mode.IN, name="projectId")
        BigDecimal projectId, @WebParam(mode = WebParam.Mode.IN, name="blockPlanId")
        BigDecimal blockPlanId, @WebParam(mode = WebParam.Mode.IN, name="gayrimenkulId")
        BigDecimal gayrimenkulId, @WebParam(mode = WebParam.Mode.IN, name="Koordinat")
        String Koordinat) throws ServiceException;

    /**
     * Exported method createVaziyetPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/createVaziyetPlani", operationName="createVaziyetPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createVaziyetPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="createVaziyetPlaniResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO createVaziyetPlani(@WebParam(mode = WebParam.Mode.IN, name="prjectId")
        BigDecimal prjectId, @WebParam(mode = WebParam.Mode.IN, name="dosyaIsmi")
        String dosyaIsmi) throws ServiceException;

    /**
     * Exported method deleteBlockPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/deleteBlockPlani", operationName="deleteBlockPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deleteBlockPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deleteBlockPlaniResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO deleteBlockPlani(@WebParam(mode = WebParam.Mode.IN, name="blokPlaniId")
        BigDecimal blokPlaniId) throws ServiceException;

    /**
     * Exported method deleteGayrimenkulGorsel from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/deleteGayrimenkulGorsel", operationName="deleteGayrimenkulGorsel")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deleteGayrimenkulGorsel")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deleteGayrimenkulGorselResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO deleteGayrimenkulGorsel(@WebParam(mode = WebParam.Mode.IN, name="GayrimenkulGorselId")
        BigDecimal GayrimenkulGorselId) throws ServiceException;

    /**
     * Exported method deletePlanGayrimenkul from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/deletePlanGayrimenkul", operationName="deletePlanGayrimenkul")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deletePlanGayrimenkul")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deletePlanGayrimenkulResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO deletePlanGayrimenkul(@WebParam(mode = WebParam.Mode.IN, name="planGayrimenkulId")
        BigDecimal planGayrimenkulId) throws ServiceException;

    /**
     * Exported method deleteVaziyetPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/deleteVaziyetPlani", operationName="deleteVaziyetPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deleteVaziyetPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="deleteVaziyetPlaniResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO deleteVaziyetPlani(@WebParam(mode = WebParam.Mode.IN, name="prjectId")
        BigDecimal prjectId) throws ServiceException;

    /**
     * Exported method getProjectDetails from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/getProjectDetails", operationName="getProjectDetails")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="getProjectDetails")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="getProjectDetailsResponse")
    @WebResult(name="result")
    List<UnitsViewSDO> getProjectDetails(@WebParam(mode = WebParam.Mode.IN, name="projectId")
        Integer projectId) throws ServiceException;

    /**
     * Exported method updateBlockPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/updateBlockPlani", operationName="updateBlockPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updateBlockPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updateBlockPlaniResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO updateBlockPlani(@WebParam(mode = WebParam.Mode.IN, name="blokPlaniId")
        BigDecimal blokPlaniId, @WebParam(mode = WebParam.Mode.IN, name="projectId")
        BigDecimal projectId, @WebParam(mode = WebParam.Mode.IN, name="blokPlaniGorseli")
        String blokPlaniGorseli, @WebParam(mode = WebParam.Mode.IN, name="KoorX")
        BigDecimal KoorX, @WebParam(mode = WebParam.Mode.IN, name="KoorY")
        BigDecimal KoorY) throws ServiceException;

    /**
     * Exported method updateGayrimenkulGorsel from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/updateGayrimenkulGorsel", operationName="updateGayrimenkulGorsel")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updateGayrimenkulGorsel")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updateGayrimenkulGorselResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO updateGayrimenkulGorsel(@WebParam(mode = WebParam.Mode.IN, name="GayrimenkulGorselId")
        BigDecimal GayrimenkulGorselId, @WebParam(mode = WebParam.Mode.IN, name="gayrimenkulId")
        BigDecimal gayrimenkulId, @WebParam(mode = WebParam.Mode.IN, name="dosyaAdi")
        String dosyaAdi, @WebParam(mode = WebParam.Mode.IN, name="baslik")
        String baslik, @WebParam(mode = WebParam.Mode.IN, name="tip")
        BigDecimal tip, @WebParam(mode = WebParam.Mode.IN, name="sira")
        BigDecimal sira) throws ServiceException;

    /**
     * Exported method updatePlanGayrimenkul from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/updatePlanGayrimenkul", operationName="updatePlanGayrimenkul")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updatePlanGayrimenkul")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updatePlanGayrimenkulResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO updatePlanGayrimenkul(@WebParam(mode = WebParam.Mode.IN, name="planGayrimenkulId")
        BigDecimal planGayrimenkulId, @WebParam(mode = WebParam.Mode.IN, name="projectId")
        BigDecimal projectId, @WebParam(mode = WebParam.Mode.IN, name="blockPlanId")
        BigDecimal blockPlanId, @WebParam(mode = WebParam.Mode.IN, name="gayrimenkulId")
        BigDecimal gayrimenkulId, @WebParam(mode = WebParam.Mode.IN, name="Koordinat")
        String Koordinat) throws ServiceException;

    /**
     * Exported method updateVaziyetPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/updateVaziyetPlani", operationName="updateVaziyetPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updateVaziyetPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="updateVaziyetPlaniResponse")
    @WebResult(name="result")
    SmartsCrudResponseSDO updateVaziyetPlani(@WebParam(mode = WebParam.Mode.IN, name="prjectId")
        BigDecimal prjectId, @WebParam(mode = WebParam.Mode.IN, name="dosyaIsmi")
        String dosyaIsmi) throws ServiceException;

    /**
     * Exported method viewBlockPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/viewBlockPlani", operationName="viewBlockPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewBlockPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewBlockPlaniResponse")
    @WebResult(name="result")
    SmartsBlokPlaniViewSDO viewBlockPlani(@WebParam(mode = WebParam.Mode.IN, name="blokPlaniId")
        BigDecimal blokPlaniId) throws ServiceException;

    /**
     * Exported method viewGayrimenkulGorsel from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/viewGayrimenkulGorsel", operationName="viewGayrimenkulGorsel")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewGayrimenkulGorsel")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewGayrimenkulGorselResponse")
    @WebResult(name="result")
    SmartsGyrmnklGorselViewSDO viewGayrimenkulGorsel(@WebParam(mode = WebParam.Mode.IN, name="GayrimenkulGorselId")
        BigDecimal GayrimenkulGorselId) throws ServiceException;

    /**
     * Exported method viewPlanGayrimenkul from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/viewPlanGayrimenkul", operationName="viewPlanGayrimenkul")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewPlanGayrimenkul")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewPlanGayrimenkulResponse")
    @WebResult(name="result")
    SmartsPlanGayrimenkulViewSDO viewPlanGayrimenkul(@WebParam(mode = WebParam.Mode.IN, name="planGayrimenkulId")
        BigDecimal planGayrimenkulId) throws ServiceException;

    /**
     * Exported method viewVaziyetPlani from SalesModule.
     */
    @WebMethod(action="/com/natica/sales/model/common/viewVaziyetPlani", operationName="viewVaziyetPlani")
    @RequestWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewVaziyetPlani")
    @ResponseWrapper(targetNamespace="/com/natica/sales/model/common/types/", localName="viewVaziyetPlaniResponse")
    @WebResult(name="result")
    SmartsVaziyetViewSDO viewVaziyetPlani(@WebParam(mode = WebParam.Mode.IN, name="projectId")
        BigDecimal projectId) throws ServiceException;
}
