package com.natica.sales.model.views.response;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 17 16:00:15 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SmartsCrudResponseRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(SmartsCrudResponseRowImpl obj) {
                return obj.getId();
            }

            public void put(SmartsCrudResponseRowImpl obj, Object value) {
                obj.setId((BigDecimal)value);
            }
        }
        ,
        ResponseCode {
            public Object get(SmartsCrudResponseRowImpl obj) {
                return obj.getResponseCode();
            }

            public void put(SmartsCrudResponseRowImpl obj, Object value) {
                obj.setResponseCode((Integer)value);
            }
        }
        ,
        Message {
            public Object get(SmartsCrudResponseRowImpl obj) {
                return obj.getMessage();
            }

            public void put(SmartsCrudResponseRowImpl obj, Object value) {
                obj.setMessage((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SmartsCrudResponseRowImpl object);

        public abstract void put(SmartsCrudResponseRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int RESPONSECODE = AttributesEnum.ResponseCode.index();
    public static final int MESSAGE = AttributesEnum.Message.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SmartsCrudResponseRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResponseCode.
     * @return the ResponseCode
     */
    public Integer getResponseCode() {
        return (Integer) getAttributeInternal(RESPONSECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResponseCode.
     * @param value value to set the  ResponseCode
     */
    public void setResponseCode(Integer value) {
        setAttributeInternal(RESPONSECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Message.
     * @return the Message
     */
    public String getMessage() {
        return (String) getAttributeInternal(MESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Message.
     * @param value value to set the  Message
     */
    public void setMessage(String value) {
        setAttributeInternal(MESSAGE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
