package com.natica.sales.model.views;

import java.math.BigDecimal;

import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 09:30:39 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SmartsBlokPlaniViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_XXNTCSMARTSBLOKPLANI = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BlokPlaniId {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getBlokPlaniId();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setBlokPlaniId((BigDecimal)value);
            }
        }
        ,
        ProjectId {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getProjectId();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setProjectId((BigDecimal)value);
            }
        }
        ,
        BlokPlaniGorseli {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getBlokPlaniGorseli();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setBlokPlaniGorseli((String)value);
            }
        }
        ,
        KoorX {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getKoorX();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setKoorX((BigDecimal)value);
            }
        }
        ,
        KoorY {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getKoorY();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setKoorY((BigDecimal)value);
            }
        }
        ,
        CreationDate {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(SmartsBlokPlaniViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(SmartsBlokPlaniViewRowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SmartsBlokPlaniViewRowImpl object);

        public abstract void put(SmartsBlokPlaniViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BLOKPLANIID = AttributesEnum.BlokPlaniId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int BLOKPLANIGORSELI = AttributesEnum.BlokPlaniGorseli.index();
    public static final int KOORX = AttributesEnum.KoorX.index();
    public static final int KOORY = AttributesEnum.KoorY.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SmartsBlokPlaniViewRowImpl() {
    }

    /**
     * Gets XxntcSmartsBlokPlani entity object.
     * @return the XxntcSmartsBlokPlani
     */
    public EntityImpl getXxntcSmartsBlokPlani() {
        return (EntityImpl)getEntity(ENTITY_XXNTCSMARTSBLOKPLANI);
    }

    /**
     * Gets the attribute value for BLOK_PLANI_ID using the alias name BlokPlaniId.
     * @return the BLOK_PLANI_ID
     */
    public BigDecimal getBlokPlaniId() {
        return (BigDecimal) getAttributeInternal(BLOKPLANIID);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOK_PLANI_ID using the alias name BlokPlaniId.
     * @param value value to set the BLOK_PLANI_ID
     */
    public void setBlokPlaniId(BigDecimal value) {
        setAttributeInternal(BLOKPLANIID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public BigDecimal getProjectId() {
        return (BigDecimal) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for BLOK_PLANI_GORSELI using the alias name BlokPlaniGorseli.
     * @return the BLOK_PLANI_GORSELI
     */
    public String getBlokPlaniGorseli() {
        return (String) getAttributeInternal(BLOKPLANIGORSELI);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOK_PLANI_GORSELI using the alias name BlokPlaniGorseli.
     * @param value value to set the BLOK_PLANI_GORSELI
     */
    public void setBlokPlaniGorseli(String value) {
        setAttributeInternal(BLOKPLANIGORSELI, value);
    }

    /**
     * Gets the attribute value for KOOR_X using the alias name KoorX.
     * @return the KOOR_X
     */
    public BigDecimal getKoorX() {
        return (BigDecimal) getAttributeInternal(KOORX);
    }

    /**
     * Sets <code>value</code> as attribute value for KOOR_X using the alias name KoorX.
     * @param value value to set the KOOR_X
     */
    public void setKoorX(BigDecimal value) {
        setAttributeInternal(KOORX, value);
    }

    /**
     * Gets the attribute value for KOOR_Y using the alias name KoorY.
     * @return the KOOR_Y
     */
    public BigDecimal getKoorY() {
        return (BigDecimal) getAttributeInternal(KOORY);
    }

    /**
     * Sets <code>value</code> as attribute value for KOOR_Y using the alias name KoorY.
     * @param value value to set the KOOR_Y
     */
    public void setKoorY(BigDecimal value) {
        setAttributeInternal(KOORY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
