package com.natica.sales.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 09:30:39 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SmartsBlokPlaniViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SmartsBlokPlaniViewImpl() {
    }
}
