package com.natica.sales.model;


import com.natica.sales.model.views.SmartsBlokPlaniViewImpl;
import com.natica.sales.model.views.SmartsBlokPlaniViewRowImpl;
import com.natica.sales.model.views.SmartsGyrmnklGorselViewImpl;
import com.natica.sales.model.views.SmartsGyrmnklGorselViewRowImpl;
import com.natica.sales.model.views.SmartsPlanGayrimenkulViewImpl;
import com.natica.sales.model.views.SmartsPlanGayrimenkulViewRowImpl;
import com.natica.sales.model.views.SmartsVaziyetViewRowImpl;
import com.natica.sales.model.views.response.SmartsCrudResponseImpl;

import com.natica.sales.model.views.response.SmartsCrudResponseRowImpl;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.VariableValueManager;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 07 11:34:11 VET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SalesModuleImpl() {
    }

    public java.util.List<ViewRowImpl> getProjectDetails(Integer projectId) {
        List<ViewRowImpl> projects = new ArrayList<ViewRowImpl>();
        ViewObjectImpl vo = getUnitsView();
        vo.setApplyViewCriteriaName("UnitsViewCriteriaByProject");
        VariableValueManager vvm = vo.ensureVariableManager();
        vvm.setVariableValue("pProjectId", projectId);
        vo.executeQuery();

        RowSetIterator iterator = vo.createRowSet(null); ///
        iterator.reset();
        while (iterator.hasNext()) {
            projects.add((ViewRowImpl)iterator.next());
        }

        return projects;
    }


    /*-------------------------------Vaziyet Planý--------------------------------------------------*/

    public SmartsCrudResponseRowImpl updateVaziyetPlani(BigDecimal prjectId, String dosyaIsmi) {
        ViewObjectImpl vo = getSmartsVaziyetView();
        filterVaziyetVo(prjectId);

        ViewObjectImpl responseVo = getSmartsCrudResponse();
        Row responseRow = responseVo.createRow();
        responseRow.setAttribute("Id", prjectId);

        if (vo.getFetchedRowCount() == 0) {
            responseRow.setAttribute("ResponseCode", new Integer(0));
            responseRow.setAttribute("Message", "Proje Bulunamadý");
        } else {
            Row row = vo.getCurrentRow();
            row.setAttribute("DosyaIsmi", dosyaIsmi);
            getTransaction().commit();

            responseRow.setAttribute("ResponseCode", new Integer(1));
            responseRow.setAttribute("Message", "Baþarýlý");
        }

        return (SmartsCrudResponseRowImpl)responseRow;
    }


    public SmartsCrudResponseRowImpl createVaziyetPlani(BigDecimal prjectId, String dosyaIsmi) {
        ViewObjectImpl requestVo = getSmartsVaziyetView();
        Row newRow = requestVo.createRow();
        newRow.setAttribute("ProjectId", prjectId);
        newRow.setAttribute("DosyaIsmi", dosyaIsmi);
        requestVo.insertRow(newRow);
        getTransaction().commit();

        ViewObjectImpl responseVo = getSmartsCrudResponse();
        Row responseRow = responseVo.createRow();
        responseRow.setAttribute("Id", prjectId);
        responseRow.setAttribute("ResponseCode", new Integer(1));
        responseRow.setAttribute("Message", "Baþarýlý");
        return (SmartsCrudResponseRowImpl)responseRow;
    }

    public SmartsVaziyetViewRowImpl viewVaziyetPlani(BigDecimal projectId) {
        ViewObjectImpl vo = getSmartsVaziyetView();
        vo.setWhereClause(null);
        vo.setWhereClause("PROJECT_ID= :pProjectId");
        vo.defineNamedWhereClauseParam("pProjectId", null, null);
        vo.setNamedWhereClauseParam("pProjectId", projectId);
        vo.executeQuery();
        vo.next();
        Row row = vo.getCurrentRow();

        return (SmartsVaziyetViewRowImpl)row;


    }

    public SmartsCrudResponseRowImpl deleteVaziyetPlani(BigDecimal prjectId) {
        ViewObjectImpl vo = getSmartsVaziyetView();
        filterVaziyetVo(prjectId);

        ViewObjectImpl responseVo = getSmartsCrudResponse();
        Row responseRow = responseVo.createRow();
        responseRow.setAttribute("Id", prjectId);

        if (vo.getFetchedRowCount() == 0) {
            responseRow.setAttribute("ResponseCode", new Integer(0));
            responseRow.setAttribute("Message", "Proje Bulunamadý");
        } else {
            Row row = vo.getCurrentRow();
            row.remove();
            getTransaction().commit();

            responseRow.setAttribute("ResponseCode", new Integer(1));
            responseRow.setAttribute("Message", "Baþarýlý");
        }

        return (SmartsCrudResponseRowImpl)responseRow;
    }

    private void filterVaziyetVo(BigDecimal projectId) {
        ViewObjectImpl vo = getSmartsVaziyetView();
        vo.setWhereClause(null);
        vo.setWhereClause("PROJECT_ID = :pProjectId");
        vo.defineNamedWhereClauseParam("pProjectId", null, null);
        vo.setNamedWhereClauseParam("pProjectId", projectId);
        vo.executeQuery();
        vo.next();
    }
    /*-------------------------------Vaziyet Planý--------------------------------------------------*/


    /*-------------------------------Plan Gayrimenkul--------------------------------------------------*/

    public SmartsCrudResponseRowImpl createPlanGayrimenkul(BigDecimal projectId, BigDecimal blockPlanId,
                                                           BigDecimal gayrimenkulId, String Koordinat) {
        ViewObjectImpl vo = getSmartsPlanGayrimenkulView();
        ViewObjectImpl respVo = getSmartsCrudResponse();
        Row addedRow = vo.createRow();
        addedRow.setAttribute("ProjeId", projectId);
        addedRow.setAttribute("BlockPlanId", blockPlanId);
        addedRow.setAttribute("GayrimenkulId", gayrimenkulId);
        addedRow.setAttribute("Koordinatlar", Koordinat);
        vo.insertRow(addedRow);
        BigDecimal primaryKey = (BigDecimal)addedRow.getAttribute("PlanGayrimenkulId");
        getTransaction().commit();

        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", primaryKey); //**************
        respRow.setAttribute("ResponseCode", new Integer(1));
        respRow.setAttribute("Message", "Baþarýlý");

        return (SmartsCrudResponseRowImpl)respRow;

    }


    public SmartsCrudResponseRowImpl updatePlanGayrimenkul(BigDecimal planGayrimenkulId, BigDecimal projectId,
                                                           BigDecimal blockPlanId, BigDecimal gayrimenkulId,
                                                           String Koordinat) {
        ViewObjectImpl vo = getSmartsPlanGayrimenkulView();
        ViewObjectImpl responseVo = getSmartsCrudResponse();

        vo.setWhereClause("PLAN_GAYRIMENKUL_ID= :pPlanGayrimenkulId");
        vo.defineNamedWhereClauseParam("pPlanGayrimenkulId", planGayrimenkulId, null);
        //vo.setNamedWhereClauseParam(arg0, arg1); //
        vo.executeQuery();
        vo.next();

        Row responseRow = responseVo.createRow();
        responseRow.setAttribute("Id", planGayrimenkulId);

        if (vo.getRowCount() == 0) {
            responseRow.setAttribute("ResponseCode", new Integer(0));
            responseRow.setAttribute("Message", "planGayrimenkulId Bulunamadý");
        } else {
            Row row = vo.getCurrentRow();
            row.setAttribute("ProjeId", projectId);
            row.setAttribute("BlockPlanId", blockPlanId);
            row.setAttribute("GayrimenkulId", gayrimenkulId);
            row.setAttribute("Koordinatlar", Koordinat);
            getTransaction().commit();

            responseRow.setAttribute("ResponseCode", new Integer(1));
            responseRow.setAttribute("Message", "Baþarýlý");
        }

        return (SmartsCrudResponseRowImpl)responseRow;

    }

    public SmartsCrudResponseRowImpl deletePlanGayrimenkul(BigDecimal planGayrimenkulId) {
        ViewObjectImpl vo = getSmartsPlanGayrimenkulView();
        ViewObjectImpl respVo = getSmartsCrudResponse();

        vo.setWhereClause("PLAN_GAYRIMENKUL_ID= :1");
        vo.setWhereClauseParam(0, planGayrimenkulId);
        vo.executeQuery();
        vo.next();

        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", planGayrimenkulId);


        if (vo.getRowCount() == 0) {
            respRow.setAttribute("ResponseCode", new Integer(0));
            respRow.setAttribute("Message", "planGayrimenkulId Bulunamadi");

        } else {
            vo.getCurrentRow().remove();
            getTransaction().commit();
            respRow.setAttribute("Message", "Basarili");
            respRow.setAttribute("ResponseCode", new Integer(1));
        }

        return (SmartsCrudResponseRowImpl)respRow;
    }


    public SmartsPlanGayrimenkulViewRowImpl viewPlanGayrimenkul(BigDecimal planGayrimenkulId) {
        ViewObjectImpl vo = getSmartsPlanGayrimenkulView();
        vo.setWhereClause("PLAN_GAYRIMENKUL_ID= :pPlanGayrimenkulId");
        vo.defineNamedWhereClauseParam("pPlanGayrimenkulId", planGayrimenkulId, null);
        vo.executeQuery();
        vo.next();

        /*     if(vo.getRowCount()==0){
               ViewObjectImpl failVo=getSmartsCrudResponse();
                Row failRow= failVo.createRow();
                   failRow.setAttribute("Id", planGayrimenkulId);
                   failRow.setAttribute("Message", "Fail: planGayrimenkulId kayitli degil");
                   failRow.setAttribute("ResponseCode", new Integer(0));
       return (SmartsCrudResponseRowImpl)failRow;
           }
       else{ */
        return (SmartsPlanGayrimenkulViewRowImpl)vo.getCurrentRow();
    }

    /*-------------------------------Plan Gayrimenkul--------------------------------------------------*/

    /*-------------------------------Gayrimenkul View--------------------------------------------------*/
    //------Create

    public SmartsCrudResponseRowImpl createGayrimenkulGorsel(BigDecimal gayrimenkulId, String dosyaAdi, String baslik,
                                                             BigDecimal tip, BigDecimal sira) {
        //BigDecimal gayrimenkulId, String dosyaAdi, String baslik, BigDecimal tip, BigDecimal sira

        ViewObjectImpl vo = getSmartsGyrmnklGorselView();
        ViewObjectImpl respVo = getSmartsCrudResponse();
        Row newRow = vo.createRow();
        newRow.setAttribute("GayrimenkulId", gayrimenkulId);
        newRow.setAttribute("DosyaAdi", dosyaAdi);
        newRow.setAttribute("Baslik", baslik);
        newRow.setAttribute("Tip", tip);
        newRow.setAttribute("Sira", sira);

        vo.insertRow(newRow);
        BigDecimal primaryKey = (BigDecimal)newRow.getAttribute("GayrimenkulGorselId");
        getTransaction().commit();
        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", primaryKey); ////////////////
        respRow.setAttribute("Message", "Basariyla Kaydedildi");
        respRow.setAttribute("ResponseCode", new Integer(1));

        return (SmartsCrudResponseRowImpl)respRow;
    }
    //-----------Update

    public SmartsCrudResponseRowImpl updateGayrimenkulGorsel(BigDecimal GayrimenkulGorselId, BigDecimal gayrimenkulId,
                                                             String dosyaAdi, String baslik, BigDecimal tip,
                                                             BigDecimal sira) {
        ViewObjectImpl vo = getSmartsGyrmnklGorselView();
        ViewObjectImpl respVo = getSmartsCrudResponse();

        vo.setWhereClause("GAYRIMENKUL_GORSEL_ID= :gGayrimenkulGorselId");
        vo.defineNamedWhereClauseParam("gGayrimenkulGorselId", GayrimenkulGorselId, null);
        vo.executeQuery();
        vo.next();

        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", GayrimenkulGorselId);

        if (vo.getRowCount() == 0) {
            respRow.setAttribute("Message", "GayrimenkulGorselId Bulunamadi");
            respRow.setAttribute("ResponseCode", new Integer(0));
        } else {
            Row currRow = vo.getCurrentRow();
            currRow.setAttribute("GayrimenkulId", gayrimenkulId);
            currRow.setAttribute("DosyaAdi", dosyaAdi);
            currRow.setAttribute("Baslik", baslik);
            currRow.setAttribute("Tip", tip);
            currRow.setAttribute("Sira", sira);
            getTransaction().commit();

            respRow.setAttribute("Message", "Basariyla Update Edilmistir");
            respRow.setAttribute("ResponseCode", new Integer(1));

        }

        return (SmartsCrudResponseRowImpl)respRow;
    }

    //----------Delete

    public SmartsCrudResponseRowImpl deleteGayrimenkulGorsel(BigDecimal GayrimenkulGorselId) {
        ViewObjectImpl vo = getSmartsGyrmnklGorselView();
        ViewObjectImpl respVo = getSmartsCrudResponse();

        vo.setWhereClause("GAYRIMENKUL_GORSEL_ID= :gGayrimenkulGorselId");
        vo.defineNamedWhereClauseParam("gGayrimenkulGorselId", GayrimenkulGorselId, null);
        vo.executeQuery();
        vo.next();

        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", GayrimenkulGorselId);

        if (vo.getRowCount() == 0) {
            respRow.setAttribute("Message", "GayrimenkulGorselId Bulunamadi");
            respRow.setAttribute("ResponseCode", new Integer(0));
        } else {
            Row currRow = vo.getCurrentRow();
            currRow.remove();
            getTransaction().commit();

            respRow.setAttribute("Message", GayrimenkulGorselId + " no'lu kayit Basariyla Silinmistir");
            respRow.setAttribute("ResponseCode", new Integer(1));

        }

        return (SmartsCrudResponseRowImpl)respRow;
    }

    //-------------------View

    public SmartsGyrmnklGorselViewRowImpl viewGayrimenkulGorsel(BigDecimal GayrimenkulGorselId) {

        ViewObjectImpl vo = getSmartsGyrmnklGorselView();
        vo.setWhereClause("GAYRIMENKUL_GORSEL_ID= :gGayrimenkulGorselId");
        vo.defineNamedWhereClauseParam("gGayrimenkulGorselId", GayrimenkulGorselId, null);
        vo.executeQuery();
        vo.next();
        return (SmartsGyrmnklGorselViewRowImpl)vo.getCurrentRow();

    }
    /*-------------------------------Gayrimenkul View--------------------------------------------------*/
    
    /*-------------------------------Block Planý View--------------------------------------------------*/
    //--------------Create

    public SmartsCrudResponseRowImpl createBlockPlani(BigDecimal projectId, String blokPlaniGorseli, BigDecimal KoorX,
                                                      BigDecimal KoorY) {
        ViewObjectImpl vo = getSmartsBlokPlaniView();
        ViewObjectImpl respVo = getSmartsCrudResponse();
        Row respRow = respVo.createRow();

        Row addRow = vo.createRow();
        addRow.setAttribute("ProjectId", projectId);
        addRow.setAttribute("BlokPlaniGorseli", blokPlaniGorseli);
        addRow.setAttribute("KoorX", KoorX);
        addRow.setAttribute("KoorY", KoorY);
        vo.insertRow(addRow);
        BigDecimal primaryKey = (BigDecimal)addRow.getAttribute("BlokPlaniId");
        getTransaction().commit();

        respRow.setAttribute("Id", primaryKey);

        respRow.setAttribute("Message", "Basariyla Olusturuldu");
        respRow.setAttribute("ResponseCode", new Integer(1));
        return (SmartsCrudResponseRowImpl)respRow;

    }

    //-------Update

    public SmartsCrudResponseRowImpl updateBlockPlani(BigDecimal blokPlaniId, BigDecimal projectId,
                                                      String blokPlaniGorseli, BigDecimal KoorX, BigDecimal KoorY) {

        ViewObjectImpl vo = getSmartsBlokPlaniView();
        ViewObjectImpl respVo = getSmartsCrudResponse();

        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", blokPlaniId);

        vo.setWhereClause("BLOK_PLANI_ID= :bBlokPlaniId");
        vo.defineNamedWhereClauseParam("bBlokPlaniId", blokPlaniId, null);
        vo.executeQuery();
        vo.next();

        if (vo.getRowCount() == 0) {
            respRow.setAttribute("Message", "bBlokPlaniId Bulunamadi");
            respRow.setAttribute("ResponseCode", new Integer(0));
        } else {

            Row currRow = vo.getCurrentRow();
            currRow.setAttribute("ProjectId", projectId);
            currRow.setAttribute("BlokPlaniGorseli", blokPlaniGorseli);
            currRow.setAttribute("KoorX", KoorX);
            currRow.setAttribute("KoorY", KoorY);
            getTransaction().commit();
            respRow.setAttribute("Message", "Basariyla Update Edildi");
            respRow.setAttribute("ResponseCode", new Integer(1));
        }
        return (SmartsCrudResponseRowImpl)respRow;
    }


    //-------------Delete

    public SmartsCrudResponseRowImpl deleteBlockPlani(BigDecimal blokPlaniId) {
        ViewObjectImpl vo = getSmartsBlokPlaniView();
        ViewObjectImpl respVo = getSmartsCrudResponse();

        vo.setWhereClause("BLOK_PLANI_ID= :bBlokPlaniId");
        vo.defineNamedWhereClauseParam("bBlokPlaniId", blokPlaniId, null);

        vo.executeQuery();
        vo.next();

        Row respRow = respVo.createRow();
        respRow.setAttribute("Id", blokPlaniId);


        if (vo.getRowCount() == 0) {
            respRow.setAttribute("Message", "bBlokPlaniId Bulunamadi");
            respRow.setAttribute("ResponseCode", new Integer(0));
        } else {
            Row currRow = vo.getCurrentRow();
            currRow.remove();
            getTransaction().commit();
            respRow.setAttribute("Message", blokPlaniId + " no'lu Kayit Basariyla Silindi");
            respRow.setAttribute("ResponseCode", new Integer(1));
        }

        return (SmartsCrudResponseRowImpl)respRow;
    }
    
    
    //----------View
    
    
    public SmartsBlokPlaniViewRowImpl viewBlockPlani(BigDecimal blokPlaniId) {
        ViewObjectImpl vo=getSmartsBlokPlaniView();
        vo.setWhereClause("BLOK_PLANI_ID= :bBlokPlaniId");
        vo.defineNamedWhereClauseParam("bBlokPlaniId", blokPlaniId, null);
        vo.executeQuery();
        vo.next();
       
        return (SmartsBlokPlaniViewRowImpl)vo.getCurrentRow();
        }
    
 /*   public ViewRowImpl viewBlockPlani2(BigDecimal blokPlaniId) {
        ViewObjectImpl vo=getSmartsBlokPlaniView();
            ViewObjectImpl respVo = getSmartsCrudResponse();
            Row respRow = respVo.createRow();
            respRow.setAttribute("Id", blokPlaniId);
            respRow.setAttribute("Message", "bBlokPlaniId Bulunamadi");
            respRow.setAttribute("ResponseCode", new Integer(0));
            
        vo.setWhereClause("BLOK_PLANI_ID= :bBlokPlaniId");
        vo.defineNamedWhereClauseParam("bBlokPlaniId", blokPlaniId, null);
        vo.executeQuery();
        vo.next();
        
        if(vo.getRowCount()==0){
                return (SmartsCrudResponseRowImpl)respRow;
            }
        else{
       
        return (SmartsBlokPlaniViewRowImpl)vo.getCurrentRow(); }
        }
*/

    /*-------------------------------Block Planý View--------------------------------------------------*/


    

    public ViewObjectImpl getUnitsView() {
        return (ViewObjectImpl)findViewObject("UnitsView");
    }

    /**
     * Container's getter for SmartsVaziyetView1.
     * @return SmartsVaziyetView1
     */
    public ViewObjectImpl getSmartsVaziyetView() {
        return (ViewObjectImpl)findViewObject("SmartsVaziyetView");
    }

    /**
     * Container's getter for SmartsCrudResponse1.
     * @return SmartsCrudResponse1
     */
    public SmartsCrudResponseImpl getSmartsCrudResponse() {
        return (SmartsCrudResponseImpl)findViewObject("SmartsCrudResponse");
    }

    /**
     * Container's getter for SmartsPlanGayrimenkulView1.
     * @return SmartsPlanGayrimenkulView1
     */
    public SmartsPlanGayrimenkulViewImpl getSmartsPlanGayrimenkulView() {
        return (SmartsPlanGayrimenkulViewImpl)findViewObject("SmartsPlanGayrimenkulView");
    }

    /**
     * Container's getter for SmartsGyrmnklGorselView1.
     * @return SmartsGyrmnklGorselView1
     */
    public SmartsGyrmnklGorselViewImpl getSmartsGyrmnklGorselView() {
        return (SmartsGyrmnklGorselViewImpl)findViewObject("SmartsGyrmnklGorselView");
    }

    /**
     * Container's getter for SmartsBlokPlaniView1.
     * @return SmartsBlokPlaniView1
     */
    public SmartsBlokPlaniViewImpl getSmartsBlokPlaniView() {
        return (SmartsBlokPlaniViewImpl)findViewObject("SmartsBlokPlaniView");
    }
}
